#!/bin/sh
# vim: set sw=4 et sts=4 tw=80 :
# Copyright 2009 Ali Polatel <polatel@gmail.com>
# Distributed under the terms of the GNU General Public License v2

if [ -z "$1" ]; then
    echo "Usage: addpredict path" >&2
    exit 1
fi

if [ -e /dev/sydbox ]; then
    :>/dev/sydbox/predict/"$1"
else
    echo "sydbox not enabled" >&2
fi
