#!/bin/sh
# vim: set sw=4 et sts=4 tw=80 :
# Copyright 2009 Ali Polatel <polatel@gmail.com>
# Distributed under the terms of the GNU General Public License v2

if [ -z "$1" ]; then
    sydbox -- bash
else
    sydbox -- "$@"
fi
